// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKbmHiyCh-PtZJejJCqspAIJhjgE1-j54',
    appId: '1:703989381905:web:57670f6b6bdfcc30076ab0',
    messagingSenderId: '703989381905',
    projectId: 'resume-data-d054d',
    authDomain: 'resume-data-d054d.firebaseapp.com',
    storageBucket: 'resume-data-d054d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfXQ55hJ8pi9W6JmwVeG_IbmaiPMI5EO8',
    appId: '1:703989381905:android:99fa0620ffa4adba076ab0',
    messagingSenderId: '703989381905',
    projectId: 'resume-data-d054d',
    storageBucket: 'resume-data-d054d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmwBU9GOk_EjpfY0207DcNs4EH9d4I_QY',
    appId: '1:703989381905:ios:70e24e717fc7a0a4076ab0',
    messagingSenderId: '703989381905',
    projectId: 'resume-data-d054d',
    storageBucket: 'resume-data-d054d.appspot.com',
    iosBundleId: 'com.masrafi.resumeios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmwBU9GOk_EjpfY0207DcNs4EH9d4I_QY',
    appId: '1:703989381905:ios:c9c891b33bd336b3076ab0',
    messagingSenderId: '703989381905',
    projectId: 'resume-data-d054d',
    storageBucket: 'resume-data-d054d.appspot.com',
    iosBundleId: 'com.example.resume.RunnerTests',
  );
}
